### PR TITLE
add tfds version warning to imagenet demo

### PR DESCRIPTION
**Pull request by brettkoonce**

### CODE REVIEW

**Comment by brettkoonce** [comment]
see also 23510fcb67a40c09aa8c8c5db230efa98d682c9a

**Comment by tomhennigan** [comment]
Hi @brettkoonce, thanks for the patch! AFAIK imagenet2012 has been [available in tfds since v1.0.0](https://github.com/tensorflow/datasets/blob/v1.0.0/docs/datasets.md#imagenet2012). Can you provide some more context on why we need to enforce a more recent version of tfds is installed?

**Comment by brettkoonce** [comment]
@tomhennigan the code requires the latest version to run, otherwise you get this error:

```
Traceback (most recent call last):
  File "/home/skoonce/.local/lib/python3.6/site-packages/google/protobuf/json_format.py", line 528, in _ConvertFieldValuePair
    [f.json_name for f in message_descriptor.fields]))
google.protobuf.json_format.ParseError: Message type "tensorflow_datasets.DatasetInfo" has no field named "moduleName".
 Available Fields(except extensions): ['name', 'description', 'version', 'configName', 'configDescription', 'citation', 'sizeInBytes', 'downloadSize', 'location', 'downloadChecksums', 'schema', 'splits', 'supervisedKeys', 'redistributionInfo']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 307, in <module>
    app.run(main)
  File "/home/skoonce/.local/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/skoonce/.local/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 268, in main
    batch = next(train_dataset)
  File "/home/skoonce/.local/lib/python3.6/site-packages/examples/imagenet/dataset.py", line 66, in load
    decoders={'image': tfds.decode.SkipDecoding()})
  File "/home/skoonce/.local/lib/python3.6/site-packages/tensorflow_datasets/core/load.py", line 341, in load
    dbuilder = builder(name, data_dir=data_dir, **builder_kwargs)
  File "/home/skoonce/.local/lib/python3.6/site-packages/tensorflow_datasets/core/load.py", line 201, in builder
    return read_only_builder.builder_from_directory(builder_dir)
  File "/home/skoonce/.local/lib/python3.6/site-packages/tensorflow_datasets/core/read_only_builder.py", line 115, in builder_from_directory
    return ReadOnlyBuilder(builder_dir=builder_dir)
  File "/home/skoonce/.local/lib/python3.6/site-packages/tensorflow_datasets/core/read_only_builder.py", line 51, in __init__
    info_proto = dataset_info.read_from_json(info_path)
  File "/home/skoonce/.local/lib/python3.6/site-packages/tensorflow_datasets/core/dataset_info.py", line 528, in read_from_json
    parsed_proto = json_format.Parse(json_str, dataset_info_pb2.DatasetInfo())
  File "/home/skoonce/.local/lib/python3.6/site-packages/google/protobuf/json_format.py", line 434, in Parse
    return ParseDict(js, message, ignore_unknown_fields, descriptor_pool)
  File "/home/skoonce/.local/lib/python3.6/site-packages/google/protobuf/json_format.py", line 454, in ParseDict
    parser.ConvertMessage(js_dict, message)
  File "/home/skoonce/.local/lib/python3.6/site-packages/google/protobuf/json_format.py", line 485, in ConvertMessage
    self._ConvertFieldValuePair(value, message)
  File "/home/skoonce/.local/lib/python3.6/site-packages/google/protobuf/json_format.py", line 599, in _ConvertFieldValuePair
    raise ParseError(str(e))
google.protobuf.json_format.ParseError: Message type "tensorflow_datasets.DatasetInfo" has no field named "moduleName".
 Available Fields(except extensions): ['name', 'description', 'version', 'configName', 'configDescription', 'citation', 'sizeInBytes', 'downloadSize', 'location', 'downloadChecksums', 'schema', 'splits', 'supervisedKeys', 'redistributionInfo']

```

**Review by tomhennigan — APPROVED** [review]

**Comment by tomhennigan** [comment]
Thanks again for the change! I discussed this a bit with some other maintainers. Its unfortunate that the TFDS version we require in imagenet is mutually exclusive with the version in transformer.

In general our preference is to require a recent version of TFDS and request the user downgrades if running the transformer example (since we don't have a clear upgrade path for that at the moment).

I'm going to follow up with this in two commits shortly, firstly adding this check and unifying it with the imagenet check to use `packaging.version` to more robustly compare version numbers. Then in a second change I will bump the required tfds version to be >=4.2 (compatible with imagenet and other examples).

**Pull request closed without merging**
