### PR TITLE
rename typing => typings

### PR DESCRIPTION
**Pull request by chris-chris**
How about changing the name from `haiku._src.typing` to `haiku._src.typings`?

There is a module name conflict between `haiku._src.typing` and the python standard library `typing`
It is a trivial issue, but I wanted to suggest the name change.

```
Error
Traceback (most recent call last):
  File "/Users/chris/anaconda3/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Users/chris/anaconda3/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/chris/anaconda3/lib/python3.7/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: stateful_test
Traceback (most recent call last):
  File "/Users/chris/anaconda3/lib/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/Users/chris/rl/haiku/haiku/_src/stateful_test.py", line 19, in <module>
    from haiku._src import base
  File "/Users/chris/rl/haiku/haiku/__init__.py", line 20, in <module>
    from haiku import data_structures
  File "/Users/chris/rl/haiku/haiku/data_structures.py", line 20, in <module>
    from haiku._src.data_structures import to_immutable_dict
  File "/Users/chris/rl/haiku/haiku/_src/data_structures.py", line 24, in <module>
    from typing import Any, Callable, Generic, Mapping, Optional, TypeVar, Tuple, Union
  File "/Users/chris/rl/haiku/haiku/_src/typing.py", line 20, in <module>
    from typing import Any, Callable, Mapping, Text, Sequence, Union
ImportError: cannot import name 'Any' from 'typing' (/Users/chris/rl/haiku/haiku/_src/typing.py)
```

### CODE REVIEW

**Comment by tomhennigan** [comment]
Hey @chris-chris, thanks for this.

We had similar feelings so the public names are `hk.$foo` rather than `hk.typing.$foo`, but I'm not a big fan of `typings` as a replacement module name. `types` would be worth considering but this has the same issue as `typing` (clashing with a builtin). Are you aware of cases where this will cause us issues?

**Comment by chris-chris** [comment]
I don't have a problem when I execute the test by `pytest`.

```
$ python -m pytest -n "${N_JOBS}" haiku/_src/reshape_test.py
```

But when I execute a single python file for the test I got a problem executing it.
The python interpreter confuses the relative path module `typing` and standard library `typing`.
I think this problem depends on the build setting and the environment variables(like PYTHONPATH). 
It will not happen when the user sets the development environment correctly.
But, trying to avoid the name conflict with the standard library will not hurt ur project.
I don't mind the new namings whether `typings` or `types` or something else.
Thanks :)

```
$ cd haiku/_src/
$ python reshape_test.py 
Traceback (most recent call last):
  File "reshape_test.py", line 20, in <module>
    from haiku._src import base
  File "/Users/chris/anaconda3/lib/python3.7/site-packages/haiku/__init__.py", line 18, in <module>
    from haiku import data_structures
  File "/Users/chris/anaconda3/lib/python3.7/site-packages/haiku/data_structures.py", line 18, in <module>
    from haiku._src.data_structures import to_immutable_dict
  File "/Users/chris/anaconda3/lib/python3.7/site-packages/haiku/_src/data_structures.py", line 22, in <module>
    from typing import Any, Callable, Generic, Mapping, Optional, TypeVar, Tuple, Union
  File "/Users/chris/rl/haiku/haiku/_src/typing.py", line 18, in <module>
    from typing import Any, Callable, Mapping, Text, Sequence, Union
ImportError: cannot import name 'Any' from 'typing' (/Users/chris/rl/haiku/haiku/_src/typing.py)
```

**Comment by inoryy** [comment]
There has to be more to it and could be fixed without the rename.  
In general, Python is well-equipped to handle module naming collisions as of [PEP328](https://www.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports).

**Comment by tomhennigan** [comment]
IIRC Python appends the current directory to PYTHONPATH hence the issue with `python reshape_test.py` when `typing.py` is in the same directory.

If you want to trigger individual tests perhaps it would be easiest to use `python -m` from the project dir:

```shell
$ python -m haiku._src.reshape_test
```

I believe this should work fine :)

**Comment by chris-chris** [comment]
Oh- I can do that! Thank you for your guidance.
Let me close this PR by myself.

**Pull request closed without merging**
