### PR TITLE
Complete annotations for Initializers

### PR DESCRIPTION
**Pull request by NeilGirdhar**
MyPy wants every parameter to be have an annotation, and it won't see the annotations without the `py.typed` file.

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
MyPy wants every parameter to be have an annotation, and it won't see the annotations without the `py.typed` file.

**Review by tomhennigan — APPROVED** [review]
I'll see if we can add a mypy presubmit to github actions. Internally we check types using pytype and afaik its all passing.

**Comment by NeilGirdhar** [comment]
@tomhennigan I think the issue is that I run MyPy with:
```
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_any_generics = True
disallow_untyped_decorators = True
```
That's why it doesn't like the implicit `Any` that the Haiku code seems to be doing.  Is it a big deal to annotate all of the parameters explicitly?

**Comment by NeilGirdhar** [comment]
Oh, I didn't notice this was merged!  Thank you!

**Comment by tomhennigan** [comment]
Thank you! Usually the copybara-service robot will handle closing out the PR on merge, not sure why that didn't happen this time 😄

**Pull request closed without merging**
